:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\CalcApi
dotnet build src\CalcApi
echo Now, run the following to start the project: dotnet run -p src\CalcApi\CalcApi.csproj --launch-profile web.
echo.
