openapi: 3.0.3
info:
  title: Calculator API
  version: 1.0.0
servers:
  - url: https://localhost:5001
paths:
  /calc:
    post:
      summary: Perform an arithmetic operation on two numbers
      tags: [calc]
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: X-Op
          required: true
          description: The arithmetic operation to perform
          schema:
            type: string
            enum: [add, sub, mul, div]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalcRequest'
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalcResponse'
        '400':
          description: Invalid input (e.g., bad header value, division by zero)
        '401':
          description: Unauthorized (missing/invalid JWT)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CalcRequest:
      type: object
      required: [number1, number2]
      properties:
        number1:
          type: number
        number2:
          type: number
    CalcResponse:
      type: object
      properties:
        result:
          type: number